# arg 1:  the new package version
post_install() {
   glib-compile-schemas /usr/share/glib-2.0/schemas > /dev/null 2>&1
	update-desktop-database -q /usr/share/applications
	update-mime-database /usr/share/mime > /dev/null 2>&1
	touch -c /usr/share/icons/hicolor
	gtk-update-icon-cache -tq /usr/share/icons/hicolor
}

post_upgrade() {
	update-desktop-database -q /usr/share/applications
	touch -c /usr/share/icons/hicolor
	gtk-update-icon-cache -tq /usr/share/icons/hicolor
}

