# arg 1:  the new package version
post_install () {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod `echo $1 | sed 's/-.//'`-rc7
}

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod `echo $1 | sed 's/-.//'`-rc7
}

