# arg 1:  the new package version
post_install () {
  #Add wheel group to handle sudouser
  groupadd -f wheel
}

## arg 1:  the new package version
## arg 2:  the old package version
pre_upgrade() {
  # Permissions of /var/db/sudo were changed from 0700 to 0711 in sudo 1.8.10
  # http://www.sudo.ws/repos/sudo/rev/5c38d77a2d0c
  if (($(vercmp $2 1.8.10-1) < 0)); then
    chmod 0711 var/db/sudo
  fi
}

# vim:set ts=2 sw=2 et:
